[workspace]
members = ["near-contract", "integration-tests", "test-token"]
exclude = ["target"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
