[package]
name = "tic-tac-toe-integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora-sdk-integration-tests = { path = "../../../aurora-rust-sdk/aurora-sdk-integration-tests" }
near-abi-client = "0.1.0"
serde = "1"
tic-tac-toe-on-near = { path = "../near-contract" }
