[package]
name = "uniswap-from-near"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aurora-sdk = { path = "../../../aurora-rust-sdk/aurora-sdk" }
serde = { version = "1", features = ["derive"] }
