[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
allow_paths = ['../../../aurora-solidity-sdk']
solc = "0.8.17"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
